/*{"k":"1.1.3","mac":"1:e6516de47106cd1b6b24f444b53643715c9009ebde78a1955121cc9be41bea24","created":"2012-12-03T22:27:20Z","version":"14061974"}*/
/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
;(function(window,document,undefined){
var g=void 0,k=!0,l=null,m=!1;function n(a){return function(){return this[a]}}var o;function p(a,c,b){var d=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){d.push.apply(d,arguments);return c.apply(a,d)}}function q(a){this.j=a;this.r=g}q.prototype.createElement=function(a,c,b){a=this.j.createElement(a);if(c)for(var d in c)c.hasOwnProperty(d)&&("style"==d?this.pa(a,c[d]):a.setAttribute(d,c[d]));b&&a.appendChild(this.j.createTextNode(b));return a};
function r(a,c,b){a=a.j.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}function s(a){function c(){document.body?a():setTimeout(c,0)}c()}function t(a){a.parentNode&&a.parentNode.removeChild(a)}function u(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return;b.push(c);a.className=b.join(" ").replace(/^\s+/,"")}
function v(a,c){for(var b=a.className.split(/\s+/),d=[],e=0,f=b.length;e<f;e++)b[e]!=c&&d.push(b[e]);a.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")}function w(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return k;return m}q.prototype.pa=function(a,c){this.U()?a.setAttribute("style",c):a.style.cssText=c};q.prototype.U=function(){if(this.r===g){var a=this.j.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.r=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.r};
function x(a,c,b,d,e,f,h){this.W=a;this.Na=c;this.wa=b;this.va=d;this.Ia=e;this.Ha=f;this.ua=h}o=x.prototype;o.getName=n("W");o.getVersion=n("Na");o.getEngine=n("wa");o.getEngineVersion=n("va");o.getPlatform=n("Ia");o.getPlatformVersion=n("Ha");o.getDocumentMode=n("ua");function z(a,c){this.c=a;this.p=c}var ba=new x("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",g);
z.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE")){a=A(this);var c=B(this),b=C(this.c,/(MSIE [\d\w\.]+)/,1);if(""!=b){var d=b.split(" "),b=d[0],d=d[1];E(d);E(c);a=new x(b,d,b,d,a,c,F(this.p))}else a=new x("MSIE","Unknown","MSIE","Unknown",a,c,F(this.p))}else if(-1!=this.c.indexOf("Opera"))a:if(c=a="Unknown",b=C(this.c,/(Presto\/[\d\w\.]+)/,1),""!=b?(c=b.split("/"),a=c[0],c=c[1]):(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=C(this.c,/rv:([^\)]+)/,1),""!=b&&(c=b)),-1!=this.c.indexOf("Opera Mini/"))b=
C(this.c,/Opera Mini\/([\d\.]+)/,1),""==b&&(b="Unknown"),a=new x("OperaMini",b,a,c,A(this),B(this),F(this.p));else{if(-1!=this.c.indexOf("Version/")&&(b=C(this.c,/Version\/([\d\.]+)/,1),""!=b)){a=new x("Opera",b,a,c,A(this),B(this),F(this.p),10<=E(b));break a}b=C(this.c,/Opera[\/ ]([\d\.]+)/,1);a=""!=b?new x("Opera",b,a,c,A(this),B(this),F(this.p),10<=E(b)):new x("Opera","Unknown",a,c,A(this),B(this),F(this.p))}else if(-1!=this.c.indexOf("AppleWebKit")){a=A(this);c=B(this);b=C(this.c,/AppleWebKit\/([\d\.]+)/,
1);""==b&&(b="Unknown");d="Unknown";-1!=this.c.indexOf("Chrome")||-1!=this.c.indexOf("CrMo")||-1!=this.c.indexOf("CriOS")?d="Chrome":-1!=this.c.indexOf("Safari")?d="Safari":-1!=this.c.indexOf("AdobeAIR")&&(d="AdobeAIR");var e="Unknown";-1!=this.c.indexOf("Version/")?e=C(this.c,/Version\/([\d\.\w]+)/,1):"Chrome"==d?e=C(this.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):"AdobeAIR"==d&&(e=C(this.c,/AdobeAIR\/([\d\.]+)/,1));"AdobeAIR"==d?(C(e,/\d+\.(\d+)/,1),2<E(e)||E(e)):(C(b,/\d+\.(\d+)/,1),526<=E(b)||E(b));
a=new x(d,e,"AppleWebKit",b,a,c,F(this.p))}else if(-1!=this.c.indexOf("Gecko")){c=a="Unknown";d=m;-1!=this.c.indexOf("Firefox")?(a="Firefox",b=C(this.c,/Firefox\/([\d\w\.]+)/,1),""!=b&&(d=C(b,/\d+\.(\d+)/,